name: dgame
description: "A new drinking game project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  intl: ^0.19.0
  camera: ^0.11.0
  file_picker: ^8.0.3
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  align_positioned: ^4.0.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  random_name_generator: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  lecle_downloads_path_provider: ^0.0.2+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
